DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS CREDITCARD;
DROP TABLE IF EXISTS TIMETABLESTATION;
DROP TABLE IF EXISTS TRAINTIMETABLE;
DROP TABLE IF EXISTS TRAIN;
DROP TABLE IF EXISTS TIMETABLE;
DROP TABLE IF EXISTS STATION;


CREATE TABLE USER (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT, USERNAME TEXT, PASSWORD TEXT);
CREATE TABLE TICKET(ID INTEGER PRIMARY KEY AUTOINCREMENT,TICKETID INTEGER,DEPARTURE TEXT, ARRIVAL TEXT, TRAIN TEXT, DEPARTUREDATE TEXT, USER REFERENCES USER(USERNAME));
CREATE TABLE CREDITCARD (ID INTEGER PRIMARY KEY AUTOINCREMENT,TYPE TEXT, NUMBER INTEGER, VALIDITY TEXT, USER REFERENCES USER(USERNAME));

CREATE TABLE STATION (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT);
CREATE TABLE TIMETABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT,DURATION INTEGER);
CREATE TABLE TIMETABLESTATION (ID INTEGER PRIMARY KEY AUTOINCREMENT,TIMETABLEID INTEGER,STATIONID INTEGER,PASSTIME INTEGER,FOREIGN KEY(TIMETABLEID) REFERENCES TIMETABLE(ID),FOREIGN KEY(STATIONID) REFERENCES STATION(ID));

CREATE TABLE TRAIN (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT);
CREATE TABLE TRAINTIMETABLE(ID INTEGER PRIMARY KEY AUTOINCREMENT, TRAINID INTEGER, TIMETABLEID INTEGER,STARTTIME DATE);


INSERT INTO `USER` (NAME,USERNAME,PASSWORD) VALUES ('Joao','joao','joao');
INSERT INTO `USER` (NAME,USERNAME,PASSWORD) VALUES ('Ze','jrnfaria','asdasdsad');

INSERT INTO `CREDITCARD` (TYPE,NUMBER,VALIDITY,USER) VALUES ('VISA',123456789,'12/2015','joao');
INSERT INTO `CREDITCARD` (TYPE,NUMBER,VALIDITY,USER) VALUES ('VISA',113456789,'12/2015','jrnfaria');


INSERT INTO 'STATION' (NAME) VALUES ('A');
INSERT INTO 'STATION' (NAME) VALUES ('A1');
INSERT INTO 'STATION' (NAME) VALUES ('Central');
INSERT INTO 'STATION' (NAME) VALUES ('B1');
INSERT INTO 'STATION' (NAME) VALUES ('B');
INSERT INTO 'STATION' (NAME) VALUES ('C');
INSERT INTO 'STATION' (NAME) VALUES ('C1');

INSERT INTO 'TIMETABLE' (NAME,DURATION) VALUES('AB',210);
INSERT INTO 'TIMETABLE' (NAME,DURATION) VALUES('BA',210);
INSERT INTO 'TIMETABLE' (NAME,DURATION) VALUES('CCENT',60);
INSERT INTO 'TIMETABLE' (NAME,DURATION) VALUES('CENTC',60);

INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,1,0);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,2,53);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,3,105);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,4,158);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,5,210);

INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,5,0);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,4,53);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,3,105);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,2,158);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,1,210);

INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,6,0);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,7,30);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,3,60);

INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(4,3,0);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(4,7,30);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,6,60);

INSERT INTO `TICKET` (TICKETID,DEPARTURE,ARRIVAL,TRAIN,DEPARTUREDATE,USER) VALUES('abcd','a','b','1','07/10/2015','joao');

INSERT INTO 'TRAIN' (NAME) VALUES('T1');
INSERT INTO 'TRAIN' (NAME) VALUES('T2');
INSERT INTO 'TRAIN' (NAME) VALUES('T3');


INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (1,1,"8:00");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (1,2,"12:00");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (1,1,"16:00");

INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (2,2,"8:00");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (2,1,"12:00");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (2,2,"16:00");


INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (3,3,"8:30");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (3,4,"10:00");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (3,3,"12:30");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (3,4,"14:00");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (3,3,"16:30");
INSERT INTO 'TRAINTIMETABLE' (TRAINID,TIMETABLEID,STARTTIME) VALUES (3,4,"18:00");

