DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS CREDITCARD;
DROP TABLE IF EXISTS TIMETABLESTATION;
DROP TABLE IF EXISTS TIMETABLE;
DROP TABLE IF EXISTS STATION;

CREATE TABLE USER (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT, USERNAME TEXT, PASSWORD TEXT);
CREATE TABLE TICKET(ID INTEGER PRIMARY KEY AUTOINCREMENT,TICKETID INTEGER,DEPARTURE TEXT, ARRIVAL TEXT, TRAIN TEXT, DEPARTUREDATE TEXT, USER REFERENCES USER(USERNAME));
CREATE TABLE CREDITCARD (ID INTEGER PRIMARY KEY AUTOINCREMENT,TYPE TEXT, NUMBER INTEGER, VALIDITY TEXT, USER REFERENCES USER(USERNAME));


CREATE TABLE STATION (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT);
CREATE TABLE TIMETABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,NAME TEXT,DURATION INTEGER);
CREATE TABLE TIMETABLESTATION (ID INTEGER PRIMARY KEY AUTOINCREMENT,TIMETABLEID INTEGER,STATIONID INTEGER,PASSTIME INTEGER,FOREIGN KEY(TIMETABLEID) REFERENCES TIMETABLE(ID),FOREIGN KEY(STATIONID) REFERENCES STATION(ID));

INSERT INTO 'STATION' (NAME) VALUES ('A');
INSERT INTO 'STATION' (NAME) VALUES ('A1');
INSERT INTO 'STATION' (NAME) VALUES ('Central');
INSERT INTO 'STATION' (NAME) VALUES ('B1');
INSERT INTO 'STATION' (NAME) VALUES ('B');
INSERT INTO 'STATION' (NAME) VALUES ('C');
INSERT INTO 'STATION' (NAME) VALUES ('C1');

INSERT INTO 'TIMETABLE' (NAME,DURATION) VALUES('AB',210);
INSERT INTO 'TIMETABLE' (NAME,DURATION) VALUES('BA',210);
INSERT INTO 'TIMETABLE' (NAME,DURATION) VALUES('CCENT',60);
INSERT INTO 'TIMETABLE' (NAME,DURATION) VALUES('CENTC',60);

INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,1,0);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,2,53);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,3,105);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,4,158);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(1,5,210);

INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,5,0);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,4,53);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,3,105);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,2,158);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(2,1,210);

INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,6,0);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,7,30);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,3,60);

INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,3,0);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,7,30);
INSERT INTO 'TIMETABLESTATION' (TIMETABLEID,STATIONID,PASSTIME) VALUES(3,6,60);

INSERT INTO `USER` (NAME,USERNAME,PASSWORD) VALUES ('Jo�o','joao','joao'),
 ('abcdef','a','b'),
 ('Ze','jrnfaria','asdasdsad');

INSERT INTO `TICKET` (TICKETID,DEPARTURE,ARRIVAL,TRAIN,DEPARTUREDATE,USER) VALUES ('abcdef','a','b','1','07/10/2015','joao');

INSERT INTO `CREDITCARD` (TYPE,NUMBER,VALIDITY,USER) VALUES ('VISA',123456789,'12/2015','joao'),
 ('2',NULL,'12/12','jrnfaria');

